name: linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: [
          {cxx: g++-7, cc: gcc-7, install: gcc-7 g++-7},
          {cxx: g++-11, cc: gcc-11, install: gcc-11 g++-11},
          {cxx: clang++-9, cc: clang-9, install: clang-9},
          {cxx: clang++-11, cc: clang-11, install: clang-11}
        ]
        build_type: [Debug, Release]
        std: [17, 20]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: |
        sudo apt update
        sudo apt install ${{matrix.compiler.install}}
        cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      working-directory: ${{github.workspace}}/build
      env:
        CC: ${{matrix.compiler.cc}}
        CXX: ${{matrix.compiler.cxx}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_STANDARD=${{matrix.std}} ${{github.workspace}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
